version: 2.1

orbs:
  clever: clever/circleci-orbs@0.2.0

workflows:
  build_test_publish:
    jobs:
      - clever/go_test:
          working_directory: ~/go/src/github.com/Clever/{{.AppName}}
          tag: "1.24"
          race: true
      - clever/go_lint:
          working_directory: ~/go/src/github.com/Clever/{{.AppName}}
          tag: "1.24"
      - clever/module_publish:
          working_directory: ~/go/src/github.com/Clever/{{.AppName}}
          filters:
            branches:
              only: master
          requires:
            - clever/go_test
            - clever/go_lint
